### ISSUE TITLE
Naming conflicts not handled

### ISSUE THREAD

**Issue by Truffula** [jashkenas/docco#303]
I'm working on an Ember-CLI project, and the naming conventions mean you have a lot of naming conflicts (multiple index.coffee etc for routes + controllers etc). As the path is not reflected in the jumpTo menu, it's impossible to distinguish between them - plus they end up overwriting each other when they get generated anyway.

If would suggest that before generating any output files, the filenames are checked for any conflicts, and if any are found, default to including the path in the jumpTo title (as has been suggestion in #252) and either name the html document differently (`controllers/index.md` --> `controllers_index.html`), or mirror the project folder structure in the `docs` folder (`controllers/index.md` --> `controllers/index.html`). The latter option would mitigate against further naming conflicts.

**Comment by olivierlesnicki** [comment]
Same here:
```
docco: app/component-1/controller.js -> docs/controller.html
docco: app/component-2/controller.js -> docs/controller.html
```
