### ISSUE TITLE
Promote `commentFilter` as a global Docco option

### ISSUE THREAD

**Issue by barraq** [jashkenas/docco#305]
Regarding #262 and other reasons (see below) I think it would be nice to promote `commentFilter` as a global Docco option. For instance the usage would become:

```
Usage: docco [options] FILES

  Options:

    -h, --help             output usage information
    -V, --version          output the version number
    -l, --layout [layout]  choose a built-in layouts (parallel, linear)
    -c, --css [file]       use a custom css file
    -o, --output [path]    use a custom output path
    -t, --template [file]  use a custom .jst template
    -e, --extension [ext]  use the given file extension for all inputs
    -L, --languages [file] use a custom languages.json
    -f, --filter [regex] use a custom comment filter
```

As #262 is pointing out, we might want some time to exclude some of our comments from the generated doc. There are many reasons for that, among them is the fact that you want to keep the generated documentation light and clear: some of the comments will be grabbed by Docco some of the comments (\eg advanced comments) will remain in the code for advanced reading.

Developers may want different policies to exclude their comments. For instance in #262 it is suggested that `all inner or indented comments should be ignored`. Other variants can be:
- all comments starting with lower case are ignored (\eg. // some comment, in coffeescript # some comment). As follow advanced comments (often inner comments) will start with a lowercase.
- all comments starting with / or # are ignored (\eg. /// some advanced comment, in coffeescript ## some advanced comment)

I think there might be other variants that can make sense.

My point is it would be awesome to let developers customize this staff.

What do you think?

**Comment by sbimikesmullin** [comment]
jash plz merge this. its messing with block strings like this, as well:

```coffee
My happy markdown text

    s = """
      blah blah blah
      #{expression}
      blah blah blah
      """
```

The expression is omitted in the Docco output.

**Comment by sbimikesmullin** [comment]
oh i just noticed github understands literate coffeescript and renders it correctly already. guess i wont need docco after all
