### ISSUE TITLE
Adding custom navigation links to processed pages

### ISSUE THREAD

**Issue by DinisCruz** [jashkenas/docco#323]
In order to help with navigating the content I would like to add a top level link (or navigation) to the generated pages that will allow the user to quickly navigate back to an index page

at the moment I started doing this https://github.com/o2platform/fluentnode/blame/a8a948e9c734fc292f53e4a3940dfbc4de23ef80/src/assert/Array.litcoffee#L1 which points to https://github.com/o2platform/fluentnode/blob/a8a948e9c734fc292f53e4a3940dfbc4de23ef80/src/fluent.litcoffee

**My first question is**: is there a better way to do this?

**My second question is:**  there a way to do this so that GitHub links (shown bellow) are not broken (which they are at the moment)

![image](https://cloud.githubusercontent.com/assets/656739/5536642/34828b9c-8a8d-11e4-94a6-2b76771404d7.png)

for reference those links work ok in the **docco** generated files:

![image](https://cloud.githubusercontent.com/assets/656739/5536777/1cc6147c-8a8f-11e4-812a-c78106d01f2d.png)

**Comment by jashkenas** [comment]
You can change the templates as you see fit, and add whatever wrapping you'd like to the HTML layouts.
