### ISSUE TITLE
Not getting the menu to other files when generating documentation

### ISSUE THREAD

**Issue by edgar-humberto** [jashkenas/docco#326]
I have been using docco in conjunction with `gulp-docco` and I have not been able to get a menu in the top right. The html files get generated but there is no menu systems.

```
function createDocumentation() {
    gulp.src(['all/my/files.js'])
        .pipe(docco({}))
        .pipe(gulp.dest('./docs'))
}
```

**Comment by OniDaito** [comment]
Seconded. This doesn't appear for either. I guess because the sources are passed one at a time into Docco I presume so the sources array is always 1 presumably?

**Comment by jashkenas** [comment]
Yes, you need to pass all of your source files together in order to generate a menu of all of them. Sounds like a bug in gulp-docco.
