### ISSUE TITLE
ENOENT Error

### ISSUE THREAD

**Issue by pexaku** [jashkenas/docco#331]
Hi,
I'v got something like that after running "docker run -p 127.0.0.1:8080:8080 swagger-ui-builder" command:

```
/usr/local/lib/node_modules/docker/src/docker.js:259
        throw err;
              ^
Error: ENOENT, lstat '/opt/swagger-ui-master/run'
```

I couldn't figure out what's wrong here, comment at this line ==
 // Something unexpected happened on the filesystem.
// Nothing really that we can do about it, so throw it and be done with it

**Comment by keithamus** [comment]
This is just a hunch, but it looks like you're trying to use [`docker`](https://github.com/jbt/docker) (the documentation generator on npm) like [`docker`](https://www.docker.com/) (the containerisation platform).

If I'm wrong and this is genuinely how you're attempting to generate documentation, then I'd suggest you file the issue with docker - https://github.com/jbt/docker.
