### ISSUE TITLE
replace paragraph symbols with section symbols

### ISSUE THREAD

**Issue by chharvey** [jashkenas/docco#332]
This issue is a repost of jashkenas/underscore#2056. Let me know if you want me to fork this repo and create a pull request.

| old | new |
| --- | --- |
| &#x00b6; | &#x00a7; |
| `&#182;` | `&#167;` |
| `.pilcrow` | `.ss` |
| `.pilwrap` | `.sswrap` |
| `class="pilcrow"` | `class="ss"` |
| `class="pilwrap"` | `class="sswrap"` |

Note: Should use Unicode hex instead of decimal: `&#182;` should be `&#x00b6;` and `&#167;`should be `&#x00a7;`, but that is another issue.

**Comment by jashkenas** [comment]
Sure, go ahead and send in a PR.
