### ISSUE TITLE
Support Markup Languages: XML and HTML

### ISSUE THREAD

**Issue by rhughes89** [jashkenas/docco#339]
I have a need to create documentation of a XML feed and Docco would be the perfect solution for adding notes for xml elements and attributes.

**Comment by jashkenas** [comment]
XML and HTML don't use inline comments. Thus, Docco can't support them.

**Comment by rhughes89** [comment]
Understood. Is there any plans of docco supporting block comments in the future? If this feature is in the project scope, I would love to contribute this feature.

**Comment by rhughes89** [comment]
This answered my question: https://github.com/jashkenas/docco/issues/142
