### ISSUE TITLE
.JADE Support

### ISSUE THREAD

**Issue by SusanthCom** [jashkenas/docco#347]
## JADE Support

**_.jade**_  support is not found in [**highlight.js**](https://highlightjs.org/static/demo/) though listed in [languages.json](https://github.com/jashkenas/docco/blob/master/resources/languages.json) as `//-`

A sample run and output :

```
$ docco foo.jade 
/usr/local/lib/node_modules/docco/node_modules/highlight.js/lib/highlight.js:443
      throw new Error('Unknown language: "' + name + '"');
      ^

Error: Unknown language: "jade"
    at Object.highlight (/usr/local/lib/node_modules/docco/node_modules/highlight.js/lib/highlight.js:443:13)
    at format (/usr/local/lib/node_modules/docco/docco.js:126:26)
    at /usr/local/lib/node_modules/docco/docco.js:47:11
    at /usr/local/lib/node_modules/docco/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
$ 
```

My humble suggestion is to add an alternative syntax highlight library support, like [**prism.js**](http://prismjs.com) 

Suggested additional command line option

```
   -s, --syntax-highlighter [highlight|prism]    select the syntax-highlighter library
```

Thank you

**Comment by jashkenas** [comment]
I'm afraid we're not going to change the syntax highlighter library just for Jade, but perhaps it should be removed from languages.json if it breaks?
