### ISSUE TITLE
Literate config file

### ISSUE THREAD

**Issue by CodeLenny** [jashkenas/docco#364]
I'm trying to write a literate Nginx configuration file, `nginx.conf.md`.  I've included the first few lines below.

``` md
# nginx Main Configuration

### Worker Processes

For better performance, set to the number of cores.

    worker_processes 1;
```

When I run `docco nginx.conf.md`, the indented code (`worker_processes 1;`) is outputted in the documentation side on the left, and not in the code side on the right.

I was under the impression that this would work, given the line in the documentation:

> Finally, the “literate” style of any language is also supported — just tack an .md extension on the end: .coffee.md, .py.md, and so on.

Did I misunderstand something, or is this unexpected behavior?

**Comment by sirlancelot** [comment]
Nginx config files don't seem to be a supported syntax according to [`resources/languages.json`](https://github.com/jashkenas/docco/blob/d0dd3cfb422ce7391f981c59e3803a38b04f4062/resources/languages.json).

**Comment by CodeLenny** [comment]
So did I misunderstand the following?

> Finally, the “literate” style of *any* language is also supported

Should it be

> Finally, the “literate” style of *any* language listed in [languages.json](https://github.com/jashkenas/docco/blob/d0dd3cfb422ce7391f981c59e3803a38b04f4062/resources/languages.json) is also supported

Also, I added a few languages to languages.json, and even with that it isn't working with this fork of Docco.  I switched over to [GerHobbelt/docco](https://github.com/GerHobbelt/docco), and it's working fine with a modified language.json:


```json
{
  [...]
  ".conf":        {"name": "nginx", "symbol": "#"},
  ".conf.md":     {"name": "nginx", "symbol": "#", "literate": true}
}
```

The name conf seems to be causing problems, but I didn't have time to debug further.

**Comment by sirlancelot** [comment]
I don't think you need that `.conf.md` line there. As adding `.md` to any supported language automatically flips the prose. The `literate` flag is for when you have a file extension that _is_ a literate syntax, such as `.litcoffee`

**Comment by jashkenas** [comment]
Yes, the language needs to be listed in languages.json, so that we know how to distinguish line comments from code.
