### ISSUE TITLE
Switch to marky-markdown?

### ISSUE THREAD

**Issue by hollowdoor** [jashkenas/docco#370]
Does everyone think it's ok to switch to `marky-markdown` for markdown parsing in some later version of docco?

There are multiple issues with the `marked` module that don't seem to be getting fixed. Like nested lists not working. I was thinking of trying a PR to  `marked`, but I saw all the old pull requests, and thought *nah*.

**Comment by jashkenas** [comment]
Doesn't seem too smart:

![image](https://cloud.githubusercontent.com/assets/4732/23616906/41c109fa-0259-11e7-9db1-2810d2c1113a.png)

Maybe send that pull request?

**Comment by hollowdoor** [comment]
There's something strange about marked. Some time ago I made my own naive markdown parser which didn't have any problems with nested lists, or nested paragraphs. I'm not sure what went wrong with marked, but they have a lexer which makes me think their parser should be working better than the crappy recursive decent markdown parser I cobbled together.

I'll try to make some time to read their source, and decide a course of action. The last merge was Jan 20th so maybe it's not a lost cause.

I'm stuck wondering why marky-markdown is so unpopular. I take your heavy handed point.

**Comment by jashkenas** [comment]
Heavy handed? Ouch ;)

I'm happy to switch to a best in class markdown parser — let's just make sure it'll continue to be maintained.

**Comment by hollowdoor** [comment]
Hehe. Maybe I'm being a little hyperbolic about the "heavy handedness". It really didn't occur to me to look at the install numbers. That could be another reason why there are a lot of issues on that particular project.

Also it just occurred to me that `marky-markdown` is actually using [markdown-it](https://www.npmjs.com/package/markdown-it) underneath (another thing I hadn't noticed before) which is comparable in installs to `marked` (marked with over 2 million, and markdown-it with over 1 million), but with a "markedly" better issue ratio for `markdown-it`. Which explains why `marky-markdown` is not very popular being npm specific with  `markdown-it` as it's more general organs. I'm thinking that because npm uses `markdown-it` that lib will be better maintained in the long run.

I might still make a PR on `marked`, but I'm still feeling `docco` could benefit from a switch to `marky-markdown`, or even to `markdown-it` (which might be better for a more generalized markdown, and not npm specific like `marky-markdown`). `markdown-it`'s plugin system looks quite nice as well. It would take some time to switch `docco` over to the other lib, and make sure it has parity with old `docco` behavior. That is unless you want to make it a major version change if you want to go through with it. As of today `markdown-it` has 847 commits. I don't think you would regret the decision to switch.

**Comment by jashkenas** [comment]
I

**Comment by jashkenas** [comment]
If you'd like to send a PR that switches over to markdown-it, and you don't mind testing it and making sure that it works better ... go right ahead.

We'll be happy to merge.

**Comment by hollowdoor** [comment]
Ok. I don't think just plopping it in will take that long, but testing will take some time. What do you think about automated testing?

**Comment by jashkenas** [comment]
> What do you think about automated testing?

I don't think they're useful for Docco, as the templates can change dramatically. 

"Should I add tests?" Would be a different PR, with probably a different answer.

**Comment by hollowdoor** [comment]
I just saw the docco.litcoffee file. Is docco using that file to generate it's own source code? I've actually never programmed in coffeescript, or literate coffee script. This should be interesting.

This might take a little longer than I thought being I'll have to learn how to use literate coffeescript. What command are you using to build with? I looked in the `package.json`, and didn't see a script. Sorry about all the questions. docco source is quite simple to read, but I've hit a little block. Does docco have to be run on it's own source, and then run `coffeescript` on it to generate the `docco.js` file?

**Comment by jashkenas** [comment]
Yes, this page:

http://jashkenas.github.io/docco/

Is the Docco source code / executable. The build command is just `cake build`.

**Comment by hollowdoor** [comment]
Oh. I missed that. Now I'll have to install cake. :)

**Comment by jashkenas** [comment]
`coffee` comes with `cake`. It's included.

**Comment by hollowdoor** [comment]
LOL. I don't know whether to laugh at my ignorance, or at how nifty coffee script idioms work together. Ok then. I think I have enough information to eventually begin. I'll probably stop bothering you now.
