### ISSUE TITLE
Vulnerable Marked dependency 

### ISSUE THREAD

**Issue by simoneduca** [jashkenas/docco#384]
Github has flagged Marked in your dependency as vulnerable. Please upgrade the dependency as GH is advising (see screenshot)
<img width="725" alt="screen shot 2018-01-15 at 13 49 40" src="https://user-images.githubusercontent.com/8989606/34945395-1d9765ca-f9fb-11e7-80aa-b558888b894b.png">

**Comment by jashkenas** [comment]
I've pushed a new version of Docco — **0.9.1** — that updates Marked to its latest version.
