### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by geoidesic** [jashkenas/docco#390]
Hi,

A few examples would go a long way towards explaining this. I read the docs but I don't get it. I can't figure out how to comment / markup my code so that docco will be able to generate documentation. The only example you show is for the README file but if I copy and paste the raw README file into a javascript file and try run docco against that then I just get errors.

I thought the idea was that you put your comments into a comment block like so:
```
/**
myFunction
======== 
is a brilliant function
*/
var myFunction = function() {

}
```
but you can't include characters that break the comment... for example, this will fail:
```
/**
myFunction
======== 
is a brilliant function
   ```bash
$ groc "lib/**/*.coffee" README.md
   
*/
var myFunction = function() {

}
```

**Comment by jashkenas** [comment]
Check out the Docco documentation page: http://ashkenas.com/docco/

That's an example. It's generated from the Docco source: https://github.com/jashkenas/docco/blob/master/docco.litcoffee

**Comment by geoidesic** [comment]
But it’s an example from a README file, not from javascript source file – as far as I can tell?
I mean if I look at the raw file it doesn’t look like something that would compile, and certainly if I did that to a javascript file it wouldn’t run in node or a browser.
https://raw.githubusercontent.com/jashkenas/docco/master/docco.litcoffee <https://raw.githubusercontent.com/jashkenas/docco/master/docco.litcoffee>

Perhaps I’m missing the point?

**Comment by jashkenas** [comment]
That `.litcoffee` file is a CoffeeScript source code file. The CoffeeScript compiler can run it directly, or compile it into JavaScript.

Here's another example, using a regular CoffeeScript file:

https://github.com/jashkenas/coffeescript/blob/master/src/cake.coffee
http://coffeescript.org/annotated-source/cake.html

And here's an example of a JavaScript file:

https://github.com/jashkenas/underscore/blob/master/underscore.js
http://underscorejs.org/docs/underscore.html
