### ISSUE TITLE
Add jsdoc format/tag support for complete API

### ISSUE THREAD

**Issue by mattjbrent** [jashkenas/docco#395]
First off, wanted to say thanks for the library. 

I was looking for a documentation generator that made sense for larger apps rather than smaller APIs. I am scoping out a documentation routine for my current employer as they currently don't have one

The default side-by-side feature really won me over.

**My idea:** The great benefit of jsdoc is the ability to clearly visualise functions with tag support allowing default consistent styling really enhances the documentation but really for any serious app, these need to be in context (both file and position in the file). I was thinking it would be amazing to get formatted jsdoc comments inline with the more verbose `//` code comments.

This would allow a developer to get really specific about their functions and the knitty gritty of params and return values but then also be able to jump out of that focus and start talking about more higher level abstractions and business rules using the existing docco format. 

I feel like this idea is pretty much missing in this space. Would love to hear your thoughts.

**Comment by jashkenas** [comment]
Sounds fine — but that's something that should be pursued in a fork, not in Docco itself: this is supposed to be a free-form documentation generation tool ... not beholden to any particular format, or any particular language.
