### ISSUE TITLE
Can I submit a PR to convert Docco to ES6?

### ISSUE THREAD

**Issue by mercmobily** [jashkenas/docco#404]
I see that there are quite a lot of PR that are not accepted and not discussed...
I don't really want to create yet another fork which is then abandoned after a few months.
Would you support me converting it to ES6?
I would essentially use decaffeinate and follow these steps:

https://gist.github.com/kvz/259ca7e60bbd5ecc336f

Coffeescript made sense a while ago, but it's a little... dated now!

**Comment by jashkenas** [comment]
Nope. It is what it is.

But feel free to fork, if you want to.
