### ISSUE TITLE
Most of the projects in "partners in crime" are abandoned or dormant

### ISSUE THREAD

**Issue by mercmobily** [jashkenas/docco#405]
Hi,

Most of the projects listed in "partners in crime" are either totally abandoned, or dormant.

Here is the full list

    // * If you're writing shell scripts, try
    // [Shocco](http://rtomayko.github.io/shocco/), a port for the **POSIX shell**,
    // also by Mr. Tomayko.

Author archived the project and marked it as "unmaintained"

    // * If **Python** is more your speed, take a look at
    // [Nick Fitzgerald](http://github.com/fitzgen)'s [Pycco](https://pycco-docs.github.io/pycco/).

This is semi-active, although it looks abandoned over the last year.

    // * For **Clojure** fans, [Fogus](http://blog.fogus.me/)'s
    // [Marginalia](http://fogus.me/fun/marginalia/) is a bit of a departure from
    // "quick-and-dirty", but it'll get the job done.

Actually maintained, but the new URL is https://github.com/gdeer81/marginalia

    // * There's a **Go** port called [Gocco](http://nikhilm.github.io/gocco/),
    // written by [Nikhil Marathe](https://github.com/nikhilm).

Last commit Apr 6, 2012

    // * For all you **PHP** buffs out there, Fredi Bach's
    // [sourceMakeup](http://jquery-jkit.com/sourcemakeup/) (we'll let the faux pas
    // with respect to our naming scheme slide), should do the trick nicely.

Last commit Mar 19, 2013

    // * **Lua** enthusiasts can get their fix with
    // [Robert Gieseke](https://github.com/rgieseke)'s [Locco](http://rgieseke.github.io/locco/).

Last commit May 2, 2014

    // * And if you happen to be a **.NET**
    // aficionado, check out [Don Wilson](https://github.com/dontangg)'s
    // [Nocco](http://dontangg.github.io/nocco/).

Last commit Feb 5, 2017, but before that there is one in May 1, 2015 and then one in 2012. There are years old unreplied pull requests.

    // * Going further afield from the quick-and-dirty, [Groc](http://nevir.github.io/groc/)
    // is a **CoffeeScript** fork of Docco that adds a searchable table of contents,
    // and aims to gracefully handle large projects with complex hierarchies of code.

Last commit Dec 12, 2014

Please consider reviewing this list.

**Comment by jashkenas** [comment]
I appreciate the links to sister projects, even if they're mostly finished. After all, Docco is mostly finished too.

**Comment by mercmobily** [comment]
Hi,

What do you mean by "mostly finished"? :D
You were a great inspiration and effectively started a small revolution!

Merc.

**Comment by jashkenas** [comment]
I mean that they work as advertised, and don't necessarily need to continually be updated. Even if unmaintained, we can still link to them.
