### ISSUE TITLE
ES6 port/rewrite done. A couple of questions...

### ISSUE THREAD

**Issue by mercmobily** [jashkenas/docco#407]
Hi Jeremy,

I wrote a while ago here, in #404 , about porting Docco to ES6. You said "It is what it is, feel free to fork".
I stared porting it, but I ended up getting a _little_ carried away. The result is something that is certainly inspired by Docco; however, it's no longer "quick and dirty". I worked on the code a _lot_, looking for the right balance between quick-and-dirty and over-engineering and over-documenting.
I would be honoured in knowing your opinion:

[es6docco.txt](https://github.com/jashkenas/docco/files/4137435/es6docco.txt)

As you can see, there is little/no resemblance with the original source. Some bits are a little more robust, and the whole thing is very documented.

I am not sure what to call it.  I feel all the names I think of (Docco Next? Docco Plus?) could potentially offend you!

I was also hoping to have the project linked to your home page once I finally publish  it onto GitHub (under a free license, obviously).

Please let me know, and thank you once again for your contributions to free software (coffeescript, backbone, underscore, etc.) and for starting what I call the "Docco movement" :D

Thanks!

Merc.

**Comment by jashkenas** [comment]
Looks nice! I hope you had fun working on it.

Feel free to send the PR adding the link to the Docco home page once you get it published up online somewhere. You can call it whatever you like — I promise I won't be offended.

**Comment by mercmobily** [comment]
Hummmm At this point I am thinking "Docco Next", "Docco plus" or "Docco 2".
I like "Docco 2" because I see my version as being really what you would have done if you were to write version 2. But, maybe I am talking myself up a little too much.

Basically, I would love to have your OK to call it "Docco 2", but ONLY if you feel that 1) It won't confuse people 2) My version is what you would have done with a small mountain of time and determination 3) You feel my code is a version 2 of yours.

But, I REALLY won't be offended if you'd rather not -- in which case I will simply name it "Docco Plus" or "Docco Next".

Thank you once again.

**Comment by jashkenas** [comment]
> Basically, I would love to have your OK to call it "Docco 2", but ONLY if you feel that 1) It won't confuse people 2) My version is what you would have done with a small mountain of time and determination 3) You feel my code is a version 2 of yours.

I think that would confuse people, and it isn't what I would have done for a version 2. Also, we don't want to have eventual confusion with a Docco v2.0 versus your project. So picking something else would be better.

**Comment by mercmobily** [comment]
All good, Docco Next or Docco Plus it is. The key is "it isn't what I would have done for a version 2." -- I respectfully accept it, and add an apology for asking.

Any hint on what I should do to lean towards what "you" see as version 2 will be very welcome -- only if you already have ideas and feel like sharing them.

Thanks again for answering!

**Comment by mercmobily** [comment]
Docco Plus it is. It was actually taken on NPM, but abandoned for 7 years by the author who gracefully transferred it to me. I will send a PR to add it to the list soon -- thank you!

**Comment by mercmobily** [comment]
I added a pull request! https://github.com/jashkenas/docco/pull/408
