### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by GitGangGuy** [jashkenas/docco#410]
Would it be possible to add svelte support (a compiler approach to modern javascript development)? Like vue, it uses js-in-html and should therefore be relatively easy to parse. I was hoping to use docco in my svelte project, and now I found out that it doesn't support the file extension :/
Here's the svelteJS website: https://svelte.dev

**Comment by jashkenas** [comment]
Sure thing — feel free to send a PR that adds the file extension, and I can merge it for you.
