### ISSUE TITLE
WATCH OUT, https://jashkenas.github.com/docco/ (linked from Github page) gives a file not found

### ISSUE THREAD

**Issue by mercmobily** [jashkenas/docco#415]
Hi,

WATCH OUT, https://jashkenas.github.com/docco/ (linked from Github page) gives a file not found!

Thanks for the awesome inspiration.

**Comment by mercmobily** [comment]
The right link should be to https://jashkenas.github.com/docco/   which then redirects to http://ashkenas.com/docco/

**Comment by silversoul93** [comment]
[https://jashkenas.github.com/docco/](https://jashkenas.github.com/docco/) does not work too.

**Comment by JJ** [comment]
https://jashkenas.github.io/docco/ Github pages use the .io domain
