### ISSUE TITLE
Omit marked sections from final output

### ISSUE THREAD

**Issue by ghost** [jashkenas/docco#69]
I am using docco for my Jasmine specs and it works really great!

But is there a way to mark sections I don't want in the final output?

That would make the documentation 100% clean because then only API code will be seen in the documentation.

Also it would be good for other cases to ignore sections.

Thanks.

**Comment by pghalliday** [comment]
What do you mean by 'part of docco proper'? I got this to work by adjusting the linear template, but then had to manually copy the rest of the linear resources as the `-t` option effectively turns off the -l option (not surprisingly really)

**Comment by justindujardin** [comment]
I meant that the -t option is now available in docco official. When I wrote the first response to this issue that was not the case. 

I'm glad you managed to get it working!

**Comment by pghalliday** [comment]
ah ok thanks :)
